/*
 * Regenerate public/sitemap.xml.
 *
 *   node scripts/generate-sitemap.mjs
 *   SITEMAP_API=http://127.0.0.1:8000 node scripts/generate-sitemap.mjs
 *
 * WHY THIS IS A SCRIPT AND NOT PART OF THE BUILD. The programme pages are rows
 * in the database, so the only honest source for the URL list is the API. But
 * making `npm run build` depend on a reachable API means a deploy fails when
 * the backend is asleep, which is a bad trade for a file that changes about
 * twice a year. So: run this by hand whenever a programme is added, removed or
 * unpublished, and commit the result.
 *
 * Unpublished programmes are absent from /public/programs, so they stay out of
 * the sitemap automatically -- which is the point. Listing a URL that returns
 * nothing is worse than not listing it.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const API = process.env.SITEMAP_API || 'https://mop-careers-api.onrender.com';
const ORIGIN = process.env.SITEMAP_ORIGIN || 'https://mopcareers.com';

// priority is a hint, not a ranking lever. The home page and the programme
// pages are what MOP wants found; the legal pages exist to be linked, not
// searched for.
const STATIC = [
  ['/', '1.0', 'weekly'],
  ['/about', '0.7', 'monthly'],
  ['/careers', '0.7', 'weekly'],
  ['/privacy-policy', '0.3', 'yearly'],
  ['/terms-of-service', '0.3', 'yearly'],
  ['/refund-policy', '0.3', 'yearly'],
];

const res = await fetch(`${API}/public/programs`);
if (!res.ok) throw new Error(`${API}/public/programs returned ${res.status}`);
const programs = await res.json();
if (!Array.isArray(programs) || programs.length === 0) {
  throw new Error('No programmes returned -- refusing to write a sitemap without them.');
}

const today = new Date().toISOString().slice(0, 10);
const url = (loc, priority, changefreq) =>
  `  <url>\n    <loc>${ORIGIN}${loc}</loc>\n    <lastmod>${today}</lastmod>\n` +
  `    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`;

const body = [
  ...STATIC.map(([loc, p, cf]) => url(loc, p, cf)),
  ...programs.map((p) => url(`/programs/${p.slug}`, '0.9', 'monthly')),
].join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'sitemap.xml');
writeFileSync(out, xml, 'utf8');
console.log(`Wrote ${out}`);
console.log(`  ${STATIC.length} static pages + ${programs.length} programmes = ${STATIC.length + programs.length} URLs`);
