"""job openings

Revision ID: 0658518fe3b9
Revises: 19f882061f3e
Create Date: 2026-08-14 22:34:59.369358
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0658518fe3b9'
down_revision: Union[str, None] = '19f882061f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('experience', sa.String(length=120), nullable=False),
    sa.Column('salary', sa.String(length=80), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_openings_sort_order'), 'job_openings', ['sort_order'], unique=False)
    # Autogenerate also wanted to swap programs.slug's unique constraint for a
    # unique index. Pre-existing drift between the model and the live schema,
    # unrelated to this table, and rewriting an index on a table the public
    # site reads on every page load does not belong here. See CLAUDE.md.

    # Seeded with the four roles that were hardcoded in Careers.jsx, so the
    # page carries on showing exactly what it showed before this migration —
    # and so an empty table means "nothing is open" rather than "not set up
    # yet". Written as data here rather than in seed.py because production
    # runs migrations on deploy and does not re-run the seed.
    op.bulk_insert(
        sa.table(
            'job_openings',
            sa.column('name', sa.String),
            sa.column('department', sa.String),
            sa.column('location', sa.String),
            sa.column('description', sa.Text),
            sa.column('experience', sa.String),
            sa.column('salary', sa.String),
            sa.column('skills', sa.JSON),
            sa.column('published', sa.Boolean),
            sa.column('sort_order', sa.Integer),
        ),
        [
            {
                'name': 'Senior Full Stack Developer',
                'department': 'Engineering',
                'location': 'Remote',
                'description': "We're looking for an experienced full-stack developer to build and maintain our learning platform. You'll work on features used by 50,000+ students daily.",
                'experience': '5-8 years',
                'salary': '₹20-30 LPA',
                'skills': ['React', 'Node.js', 'PostgreSQL', 'AWS'],
                'published': True,
                'sort_order': 10,
            },
            {
                'name': 'Placement Manager',
                'department': 'Placement Team',
                'location': 'Bangalore',
                'description': 'Lead our placement efforts by building relationships with companies and ensuring our students land great jobs. A key role in our mission.',
                'experience': '3-5 years in HR/Placement',
                'salary': '₹12-18 LPA',
                'skills': ['HR', 'Communication', 'Relationship Management'],
                'published': True,
                'sort_order': 20,
            },
            {
                'name': 'Instructor - Web Development',
                'department': 'Education',
                'location': 'Hybrid',
                'description': 'Teach our Full Stack and Web Development courses to passionate students. Create engaging content and mentor the next generation of developers.',
                'experience': '3-7 years in web development',
                'salary': '₹10-16 LPA',
                'skills': ['React', 'Teaching', 'Mentoring'],
                'published': True,
                'sort_order': 30,
            },
            {
                'name': 'Content Writer',
                'department': 'Marketing',
                'location': 'Remote',
                'description': 'Create compelling content for our website, blogs, and marketing materials. Help us tell our story and reach more students.',
                'experience': '2-4 years',
                'salary': '₹8-12 LPA',
                'skills': ['Writing', 'SEO', 'Content Strategy'],
                'published': True,
                'sort_order': 40,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_openings_sort_order'), table_name='job_openings')
    op.drop_table('job_openings')
    # ### end Alembic commands ###
