"""leader section

Revision ID: 102c0b5b1f66
Revises: 8be5e8785cc0
Create Date: 2026-08-14 23:09:00.905259
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '102c0b5b1f66'
down_revision: Union[str, None] = '8be5e8785cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required, not decorative: autogenerate proposed a NOT
    # NULL column with no default, which cannot be added to a table that
    # already holds the CEO and the Director. Existing rows become
    # 'leadership', which is where they already were.
    op.add_column(
        'leaders',
        sa.Column('section', sa.String(length=20), nullable=False, server_default='leadership'),
    )
    op.create_index(op.f('ix_leaders_section'), 'leaders', ['section'], unique=False)
    # The programs.slug index churn is pre-existing drift, dropped here as in
    # the previous three migrations. See CLAUDE.md.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaders_section'), table_name='leaders')
    op.drop_column('leaders', 'section')
    # ### end Alembic commands ###
