"""job applications

Revision ID: 19f882061f3e
Revises: d1c73f9b2e46
Create Date: 2026-08-14 08:26:55.993621
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '19f882061f3e'
down_revision: Union[str, None] = 'd1c73f9b2e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('years_experience', sa.String(length=40), nullable=False),
    sa.Column('resume_url', sa.String(length=500), nullable=False),
    sa.Column('portfolio_url', sa.String(length=300), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_email'), 'job_applications', ['email'], unique=False)
    # Autogenerate also wanted to swap programs.slug's unique constraint for a
    # unique index. That is pre-existing drift between the model and the live
    # schema, unrelated to this table, and rewriting an index on a table the
    # public site reads on every page load does not belong in a migration about
    # job applications. Deliberately dropped — see CLAUDE.md.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_email'), table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
