"""add programme to enquiries

Revision ID: 5f5f76aedd76
Revises: 1ad1c59d1879
Create Date: 2026-07-27 12:44:19.842752
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f5f76aedd76'
down_revision: Union[str, None] = '1ad1c59d1879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('programme', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'programme')
    # ### end Alembic commands ###
