"""leaders

Revision ID: 8be5e8785cc0
Revises: 0658518fe3b9
Create Date: 2026-08-14 22:48:22.821946
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8be5e8785cc0'
down_revision: Union[str, None] = '0658518fe3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('meta', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaders_sort_order'), 'leaders', ['sort_order'], unique=False)
    # The programs.slug index churn autogenerate keeps proposing is pre-existing
    # drift, unrelated to this table, and dropped here for the third time. See
    # CLAUDE.md — it wants fixing deliberately, not as a side effect.

    # The two leaders who were hardcoded on the About page, so it carries on
    # showing what it showed before. Bios keep their paragraph breaks: the page
    # splits on blank lines. No photo_url — the portraits on mopcareers.in are
    # Unsplash stock of unrelated people, so initials are the honest default
    # until MOP supplies real ones.
    op.bulk_insert(
        sa.table(
            'leaders',
            sa.column('name', sa.String),
            sa.column('role', sa.String),
            sa.column('tags', sa.JSON),
            sa.column('meta', sa.String),
            sa.column('bio', sa.Text),
            sa.column('photo_url', sa.String),
            sa.column('published', sa.Boolean),
            sa.column('sort_order', sa.Integer),
        ),
        [
            {
                'name': 'Kakarla Venkata Balakrishna',
                'role': 'CEO — MOP Careers',
                'tags': ['Ex-Capgemini', 'Ex-Wipro'],
                'meta': '15+ Years · Data Science',
                'bio': (
                    'Kakarla Venkata Balakrishna, CEO of MOP Careers, brings over 15 years of '
                    'professional experience in Data Science with organizations such as Capgemini '
                    'and Wipro.\n\n'
                    'With a strong focus on practical, industry-oriented learning, he is committed '
                    'to helping learners bridge the gap between education, real-world skills, and '
                    'career opportunities.\n\n'
                    'His vision for MOP Careers is to create accessible, practical, and '
                    'career-focused learning programs that help freshers, graduates, and career '
                    'switchers become job-ready.'
                ),
                'photo_url': '',
                'published': True,
                'sort_order': 10,
            },
            {
                'name': 'Marri Kasivishalakshi',
                'role': 'Director — MOP Careers',
                'tags': ['Ex-Fidelity', 'Ex-Dukaan'],
                'meta': '10+ Years · Digital Marketing',
                'bio': (
                    'Marri Kasivishalakshi, Director of MOP Careers, brings over 10 years of '
                    'experience in Digital Marketing, with professional experience at Fidelity '
                    'and Dukaan.\n\n'
                    'She brings practical industry knowledge and a strong focus on helping '
                    'learners develop real-world digital marketing skills that can be applied in '
                    'modern business environments.\n\n'
                    "As Director, she contributes to MOP Careers' vision of combining quality "
                    'training, practical projects, expert mentorship, and career-focused learning.'
                ),
                'photo_url': '',
                'published': True,
                'sort_order': 20,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaders_sort_order'), table_name='leaders')
    op.drop_table('leaders')
    # ### end Alembic commands ###
