"""Seed the database with a working demo dataset.

Run with:  python -m app.seed        (add --reset to wipe Phase 1 data first)

Idempotent: re-running updates the existing rows rather than duplicating them.
"""
import argparse
import random
import sys
from datetime import date, timedelta

from sqlalchemy import delete, func, select
from sqlalchemy.orm import Session

from app.config import NOTES_DIR
from app.curriculum import ensure_curriculum
from app.database import SessionLocal
from app.models import (
    BATCH_ACTIVE,
    DAY_COMPLETED,
    ROLE_ADMIN,
    ROLE_STUDENT,
    ROLE_TEACHER,
    Application,
    Attendance,
    Batch,
    Company,
    CurriculumDay,
    FeePayment,
    FeeRecord,
    InterviewRound,
    Milestone,
    PasswordResetToken,
    TeacherBatch,
    User,
)
from app.security import hash_password

BATCH_NAME = "PFS-2026-JAN"
COMPLETED_THROUGH_DAY = 8   # days 1-8 are "already taught" so dashboards have data

ADMIN = {"name": "MOP Administrator", "email": "admin@mopcareers.com", "password": "Admin@123", "phone": "9000000001"}
TEACHER = {"name": "Ravi Kumar", "email": "ravi.kumar@mopcareers.com", "password": "Teacher@123", "phone": "9000000002"}

STUDENTS = [
    {"name": "Aditya Sharma",  "email": "aditya.sharma@example.com",  "phone": "9000000101", "yoe_it": 0.0},
    {"name": "Bhavana Reddy",  "email": "bhavana.reddy@example.com",  "phone": "9000000102", "yoe_it": 1.5},
    {"name": "Charan Teja",    "email": "charan.teja@example.com",    "phone": "9000000103", "yoe_it": 2.0},
    {"name": "Divya Nair",     "email": "divya.nair@example.com",     "phone": "9000000104", "yoe_it": 0.0},
    {"name": "Eshwar Prasad",  "email": "eshwar.prasad@example.com",  "phone": "9000000105", "yoe_it": 3.0},
]
STUDENT_PASSWORD = "Student@123"

# Only the last student keeps must_change_password=True, so the forced-change
# screen can be exercised in the UI while the other logins stay usable for testing.
FORCE_CHANGE_EMAIL = STUDENTS[-1]["email"]


def make_notes_pdf(day_number: int, topic: str, batch_name: str) -> str:
    """Write a placeholder notes PDF for a taught day and return its filename.

    Without this, no seeded day has notes and the student's "Notes PDF" button
    never appears — leaving that path invisible in the demo.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    filename = f"seed_{batch_name.lower()}_day{day_number}.pdf"
    path = NOTES_DIR / filename

    c = canvas.Canvas(str(path), pagesize=A4)
    width, height = A4

    c.setFillColorRGB(0.043, 0.118, 0.275)   # navy #0B1E46
    c.rect(0, height - 28 * mm, width, 28 * mm, stroke=0, fill=1)
    c.setFillColorRGB(1, 1, 1)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(20 * mm, height - 18 * mm, "MOP CAREERS")

    c.setFillColorRGB(0.043, 0.118, 0.275)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(20 * mm, height - 45 * mm, f"Day {day_number} - {topic}")

    c.setFillColorRGB(0, 0.596, 0.616)       # teal #00989D
    c.setFont("Helvetica", 11)
    c.drawString(20 * mm, height - 53 * mm, f"Batch {batch_name}  |  Python Full Stack")

    c.setFillColorRGB(0.2, 0.2, 0.2)
    c.setFont("Helvetica", 10.5)
    lines = [
        "",
        "These are placeholder class notes generated by the seed script.",
        "Your instructor will replace them with the real notes for this session.",
        "",
        "In this session we cover:",
        f"  -  An introduction to {topic.lower()}",
        "  -  Worked examples written live in class",
        "  -  Common mistakes and how to avoid them",
        "  -  Practice exercises to complete before the next class",
    ]
    y = height - 68 * mm
    for line in lines:
        c.drawString(20 * mm, y, line)
        y -= 6 * mm

    c.setFont("Helvetica-Oblique", 8.5)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(20 * mm, 15 * mm, "MOP Careers - Python Full Stack programme")

    c.showPage()
    c.save()
    return filename


def upsert_user(db: Session, *, name: str, email: str, password: str, role: str,
                phone: str | None = None, must_change: bool = False,
                yoe_it: float | None = None, batch_id: int | None = None) -> User:
    user = db.scalar(select(User).where(User.email == email))
    if user is None:
        user = User(email=email)
        db.add(user)
    user.name = name
    user.phone = phone
    user.role = role
    user.password_hash = hash_password(password)
    user.must_change_password = must_change
    user.is_blocked = False
    user.yoe_it = yoe_it
    user.batch_id = batch_id
    db.flush()
    return user


def reset_data(db: Session) -> None:
    """Drop all seeded rows. Destructive — only runs behind --reset.

    Order matters: children before parents.
    """
    db.execute(delete(InterviewRound))
    db.execute(delete(Application))
    db.execute(delete(Company))
    db.execute(delete(FeePayment))
    db.execute(delete(FeeRecord))
    db.execute(delete(Attendance))
    db.execute(delete(PasswordResetToken))
    db.execute(delete(CurriculumDay))
    db.execute(delete(TeacherBatch))
    db.execute(delete(Milestone))
    db.execute(delete(User))
    db.execute(delete(Batch))
    db.commit()
    print("  Cleared existing data.")


TOTAL_FEE = 45000.00

# (fee paid so far, [(amount, days_after_start, mode)]) per student, in order.
# Deliberately varied so the pending-balance list and collection summary have
# something meaningful to show: one paid in full, one unpaid, three partway.
FEE_PLAN = [
    [(20000, 0, "UPI"), (25000, 20, "bank")],   # Aditya  - paid in full
    [(15000, 1, "UPI")],                        # Bhavana - part paid
    [(20000, 2, "cash"), (10000, 25, "UPI")],   # Charan  - part paid
    [],                                         # Divya   - nothing yet
    [(45000, 3, "bank")],                       # Eshwar  - paid in full
]

COMPANIES = [
    ("Infosys", "https://infosys.com", "Bengaluru"),
    ("TCS", "https://tcs.com", "Hyderabad"),
    ("Zoho", "https://zoho.com", "Chennai"),
    ("Freshworks", "https://freshworks.com", "Chennai"),
]

# (student index, company index, role, status, package_lpa, [(round, result)])
APPLICATIONS = [
    (0, 0, "Python Full Stack Developer", "joined", 6.5,
     [("Online Assessment", "passed"), ("Technical Round 1", "passed"), ("HR Round", "passed")]),
    (0, 1, "Software Engineer Trainee", "rejected", None,
     [("Aptitude Test", "failed")]),
    (1, 2, "Backend Developer", "offered", 7.2,
     [("Technical Screen", "passed"), ("System Design", "passed"), ("HR Round", "passed")]),
    (1, 3, "Associate Engineer", "interviewing", None,
     [("Online Assessment", "passed"), ("Technical Round 1", "pending")]),
    (2, 0, "Python Developer", "shortlisted", None, []),
    (3, 1, "Graduate Engineer Trainee", "applied", None, []),
    (4, 3, "Full Stack Engineer", "offered", 8.0,
     [("Coding Round", "passed"), ("Technical Round", "passed"), ("Hiring Manager", "passed")]),
]


def seed_phase2(db: Session, students: list[User], start: date) -> None:
    """Fees and placements demo data."""
    # --- fees ---------------------------------------------------------
    payments_made = 0
    for student, plan in zip(students, FEE_PLAN):
        record = db.scalar(select(FeeRecord).where(FeeRecord.student_id == student.id))
        if record is None:
            record = FeeRecord(student_id=student.id)
            db.add(record)
        record.total_fee = TOTAL_FEE
        record.notes = "Standard Python Full Stack programme fee."
        db.flush()

        existing = db.scalar(
            select(func.count(FeePayment.id)).where(FeePayment.student_id == student.id)
        )
        if existing:
            continue
        for amount, offset, mode in plan:
            db.add(
                FeePayment(
                    student_id=student.id,
                    amount=amount,
                    paid_on=start + timedelta(days=offset),
                    mode=mode,
                    reference=f"REF{student.id:03d}{offset:03d}",
                )
            )
            payments_made += 1

    fully_paid = sum(1 for p in FEE_PLAN if sum(a for a, _, _ in p) >= TOTAL_FEE)
    print(f"  Fees: {len(students)} records at {TOTAL_FEE:,.0f}, {payments_made} payments "
          f"({fully_paid} paid in full)")

    # --- companies ----------------------------------------------------
    companies: list[Company] = []
    for name, website, location in COMPANIES:
        c = db.scalar(select(Company).where(Company.name == name))
        if c is None:
            c = Company(name=name, website=website, location=location)
            db.add(c)
            db.flush()
        companies.append(c)

    # --- applications + rounds ----------------------------------------
    created = 0
    for s_idx, c_idx, role, status_, package, rounds in APPLICATIONS:
        student = students[s_idx]
        company = companies[c_idx]
        existing = db.scalar(
            select(Application).where(
                Application.student_id == student.id,
                Application.company_id == company.id,
                Application.role_title == role,
            )
        )
        if existing:
            continue

        app = Application(
            student_id=student.id,
            company_id=company.id,
            role_title=role,
            status=status_,
            package_lpa=package,
            applied_on=start + timedelta(days=30 + s_idx * 2),
        )
        db.add(app)
        db.flush()
        created += 1

        for i, (round_name, result) in enumerate(rounds):
            db.add(
                InterviewRound(
                    application_id=app.id,
                    round_name=round_name,
                    scheduled_on=start + timedelta(days=32 + s_idx * 2 + i * 3),
                    result=result,
                    feedback="Handled the questions well." if result == "passed" else None,
                )
            )

    placed = len({a[0] for a in APPLICATIONS if a[3] in ("offered", "joined")})
    print(f"  Placements: {len(companies)} companies, {created} applications, "
          f"{placed} of {len(students)} students placed")


def seed(reset: bool = False) -> None:
    db = SessionLocal()
    try:
        print("Seeding MOP Careers demo data...")
        if reset:
            reset_data(db)

        # --- admin --------------------------------------------------------
        upsert_user(db, name=ADMIN["name"], email=ADMIN["email"], password=ADMIN["password"],
                    role=ROLE_ADMIN, phone=ADMIN["phone"], must_change=False)
        print(f"  Admin:   {ADMIN['email']} / {ADMIN['password']}")

        # --- batch --------------------------------------------------------
        start = date.today() - timedelta(days=COMPLETED_THROUGH_DAY * 2)
        batch = db.scalar(select(Batch).where(Batch.name == BATCH_NAME))
        if batch is None:
            batch = Batch(name=BATCH_NAME)
            db.add(batch)
        batch.course_type = "Python Full Stack"
        batch.start_date = start
        batch.status = BATCH_ACTIVE
        db.flush()

        ensure_curriculum(db, batch.id)
        db.flush()
        print(f"  Batch:   {batch.name} (55 curriculum days)")

        # --- teacher ------------------------------------------------------
        teacher = upsert_user(db, name=TEACHER["name"], email=TEACHER["email"],
                              password=TEACHER["password"], role=ROLE_TEACHER,
                              phone=TEACHER["phone"], must_change=False)
        if not db.scalar(
            select(TeacherBatch).where(
                TeacherBatch.teacher_id == teacher.id, TeacherBatch.batch_id == batch.id
            )
        ):
            db.add(TeacherBatch(teacher_id=teacher.id, batch_id=batch.id))
        print(f"  Teacher: {TEACHER['email']} / {TEACHER['password']}  -> {batch.name}")

        # --- students -----------------------------------------------------
        students: list[User] = []
        for spec in STUDENTS:
            force = spec["email"] == FORCE_CHANGE_EMAIL
            s = upsert_user(db, name=spec["name"], email=spec["email"],
                            password=STUDENT_PASSWORD, role=ROLE_STUDENT,
                            phone=spec["phone"], must_change=force,
                            yoe_it=spec["yoe_it"], batch_id=batch.id)
            students.append(s)

            ms = db.scalar(select(Milestone).where(Milestone.student_id == s.id))
            if ms is None:
                ms = Milestone(student_id=s.id)
                db.add(ms)
            ms.enrolled = start - timedelta(days=10)
            ms.batch_assigned = start - timedelta(days=3)
            ms.batch_started = start
            db.flush()
        print(f"  Students: {len(students)} enrolled, password {STUDENT_PASSWORD}")
        print(f"            ({FORCE_CHANGE_EMAIL} must change password on first login)")

        # --- mark early days taught, with attendance ----------------------
        rng = random.Random(20260125)   # fixed seed keeps the demo reproducible
        days = db.scalars(
            select(CurriculumDay)
            .where(CurriculumDay.batch_id == batch.id)
            .order_by(CurriculumDay.day_number)
        ).all()

        for day in days:
            if day.day_number <= COMPLETED_THROUGH_DAY:
                day.scheduled_date = start + timedelta(days=(day.day_number - 1) * 2)
                day.status = DAY_COMPLETED
                day.recording_url = (
                    f"https://recordings.mopcareers.com/{batch.name.lower()}/day-{day.day_number}"
                )
                if not day.notes_file:
                    day.notes_file = make_notes_pdf(day.day_number, day.topic, batch.name)
            elif day.day_number <= COMPLETED_THROUGH_DAY + 6:
                # Next few classes get dates so the Schedule page has content.
                day.scheduled_date = start + timedelta(days=(day.day_number - 1) * 2)
        db.flush()

        completed_days = [d for d in days if d.day_number <= COMPLETED_THROUGH_DAY]
        existing = {
            (a.student_id, a.curriculum_day_id)
            for a in db.scalars(select(Attendance)).all()
        }
        marked = 0
        for student in students:
            for day in completed_days:
                if (student.id, day.id) in existing:
                    continue
                # ~85% present, so Missed Classes is not empty.
                db.add(
                    Attendance(
                        student_id=student.id,
                        curriculum_day_id=day.id,
                        present=rng.random() < 0.85,
                    )
                )
                marked += 1
        print(f"  Curriculum: days 1-{COMPLETED_THROUGH_DAY} marked complete "
              f"(recording links + notes PDFs), {marked} attendance records created")

        db.flush()
        seed_phase2(db, students, start)

        db.commit()
        print("\nSeed complete.")
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed MOP Careers demo data.")
    parser.add_argument("--reset", action="store_true", help="delete existing Phase 1 data first")
    args = parser.parse_args()
    try:
        seed(reset=args.reset)
    except Exception as exc:  # pragma: no cover
        print(f"\nSeed failed: {type(exc).__name__}: {exc}", file=sys.stderr)
        raise SystemExit(1)
